### ISSUE TITLE
Please provide a preview :D

### ISSUE THREAD

**Issue by matbrgz** [DuarteMartinho/clone_twitch#1]
If possible, deploy to Vercel or take a screenshot. Thank you.

**Comment by DuarteMartinho** [comment]
Will do @matbrgz, currently a WIP! 
Thanks

**Comment by matbrgz** [comment]
Just an example made using shadcn ui -> https://github.com/niu-grandpa/game-live-platform

**Comment by DuarteMartinho** [comment]
I m following that tutorial ;)
